### ISSUE TITLE
featuretools

### ISSUE THREAD

**Issue by ylHe** [JYLFamily/Home_Credit_Default_Risk#1]
请问使用featuretools和手动构造特征，最终哪个效果更好一些呢？有什么建议？谢谢

**Comment by JYLFamily** [comment]
> 请问使用featuretools和手动构造特征，最终哪个效果更好一些呢？有什么建议？谢谢

不好意思现在才看到。 FeatureTools 更多是做变换、聚合特征，手工特征更多是特征间的加减乘除。我认为应该二者组合起来一并使用。
